#/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 0
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 1
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 2
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 3
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 4
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 5
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 6
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 7
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 8
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 9
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 10
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 11
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 12
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 13
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 14
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 15
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 16
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 17
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 18
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 19
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 20
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 21
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 22
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 23
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 24
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 25
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 26
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 27
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 28
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 29
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 30
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 31
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 32
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 33
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 34
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 35
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 36
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 37
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 38
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 39
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 40
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 41
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 42
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 43
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 44
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 45
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 46
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 47
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 48
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 49
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 50
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 51
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 52
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 53
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 54
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 55
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 56
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 57
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 58
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 59
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 60
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 61
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 62
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 63
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 64
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 65
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 66
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 67
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 68
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 69
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 70
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 71
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 72
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 73
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 74
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 75
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 76
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 77
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 78
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 79
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 80
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 81
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 82
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 83
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 84
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 85
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 86
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 87
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 88
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 89
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 90
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 91
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 92
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 93
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 94
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 95
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 96
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 97
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 98
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 99
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 100
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 101
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 102
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 103
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 104
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 105
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 106
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 107
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 108
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 109
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 110
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 111
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 112
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 113
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 114
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 115
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 116
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 117
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 118
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 119
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 120
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 121
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 122
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 123
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 124
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 125
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 126
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 127
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 128
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 129
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 130
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 131
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 132
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 133
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 134
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 135
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 136
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 137
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 138
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 139
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 140
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 141
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 142
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 143
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 144
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 145
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 146
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 147
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 148
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 149
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 150
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 151
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 152
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 153
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 154
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 155
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 156
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 157
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 158
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 159
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 160
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 161
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 162
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 163
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 164
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 165
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 166
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 167
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 168
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 169
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 170
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 171
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 172
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 173
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 174
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 175
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 176
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 177
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 178
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 179
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 180
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 181
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 182
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 183
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 184
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 185
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 186
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 187
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 188
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 189
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 190
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 191
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 192
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 193
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 194
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 195
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 196
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 197
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 198
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 199
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 200
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 201
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 202
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 203
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 204
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 205
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 206
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 207
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 208
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 209
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 210
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 211
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 212
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 213
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 214
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 215
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 216
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 217
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 218
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 219
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 220
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 221
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 222
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 223
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 224
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 225
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 226
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 227
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 228
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 229
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 230
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 231
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 232
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 233
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 234
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 235
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 236
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 237
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 238
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 239
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 240
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 241
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 242
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 243
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 244
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 245
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 246
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 247
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 248
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 249
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 250
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 251
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 252
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 253
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 254
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 255
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 256
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 257
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 258
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 259
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 260
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 261
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 262
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 263
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 264
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 265
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 266
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 267
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 268
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 269
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 270
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 271
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 272
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 273
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 274
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 275
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 276
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 277
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 278
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 279
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 280
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 281
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 282
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 283
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 284
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 285
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 286
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 287
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 288
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 289
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 290
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 291
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 292
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 293
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 294
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 295
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 296
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 297
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 298
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 299
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 300
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 301
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 302
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 303
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 304
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 305
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 306
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 307
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 308
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 309
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 310
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 311
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 312
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 313
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 314
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 315
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 316
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 317
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 318
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 319
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 320
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 321
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 322
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 323
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 324
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 325
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 326
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 327
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 328
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 329
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 330
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 331
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 332
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 333
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 334
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 335
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 336
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 337
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 338
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 339
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 340
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 341
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 342
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 343
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 344
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 345
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 346
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 347
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 348
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 349
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 350
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 351
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 352
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 353
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 354
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 355
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 356
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 357
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 358
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 359
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 360
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 361
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 362
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 363
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 364
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 365
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 366
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 367
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 368
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 369
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 370
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 371
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 372
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 373
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 374
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 375
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 376
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 377
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 378
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 379
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 380
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 381
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 382
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 383
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 384
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 385
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 386
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 387
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 388
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 389
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 390
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 391
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 392
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 393
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 394
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 395
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 396
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 397
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 398
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 399
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 400
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 401
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 402
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 403
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 404
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 405
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 406
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 407
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 408
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 409
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 410
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 411
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 412
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 413
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 414
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 415
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 416
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 417
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 418
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 419
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 420
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 421
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 422
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 423
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 424
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 425
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 426
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 427
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 428
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 429
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 430
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 431
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 432
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 433
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 434
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 435
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 436
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 437
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 438
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 439
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 440
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 441
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 442
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 443
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 444
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 445
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 446
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 447
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 448
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 449
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 450
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 451
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 452
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 453
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 454
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 455
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 456
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 457
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 458
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 459
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 460
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 461
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 462
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 463
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 464
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 465
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 466
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 467
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 468
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 469
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 470
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 471
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 472
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 473
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 474
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 475
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 476
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 477
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 478
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 479
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 480
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 481
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 482
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 483
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 484
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 485
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 486
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 487
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 488
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 489
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 490
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 491
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 492
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 493
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 494
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 495
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 496
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 497
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 498
/opt/anaconda3/envs/kronos/bin/python /Users/longquan/PycharmProjects/Kronos-web/update_predictions.py --step 499
